version: '3.6'
services:
  redis:
    image: redis:alpine
    container_name: oneblock-redis
    command: redis-server --save 60 1 --loglevel warning
    hostname: redis
    expose:
      - 6379
    volumes:
      - ./redis:/data

  server:
    build: ./server
    container_name: oneblock-server
    depends_on:
      - redis
    environment:
      - SERVER_PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379 # optional
      - REDIS_PASSWORD= # optional
    ports:
      - 127.0.0.1:8080:8080
