version: '3.6'
services:
  redis:
    image: redis:alpine
    container_name: oneblock-redis
    hostname: redis
    expose:
      - 6379

  oneblock:
    image: oneblock:latest
    container_name: oneblock
    depends_on:
      - redis
    environment:
      - CAPTCHA_CHALLENGER_PATH=/usr/src/app/hcaptcha-challenger
      - CAPTCHA_CHALLENGER_ENTRYPOINT=python3
      - MINECRAFT_USERNAME=Rakox
      - REDIS_HOST=redis
    volumes:
      - ./screenshots:/usr/src/app/screenshots
      - ./database:/usr/src/app/hcaptcha_challenger/src/database
    ports:
      - 127.0.0.1:7777:7777
